### ISSUE TITLE
Load plugin textdomain

### ISSUE THREAD

**Issue by GaryJones** [meitar/wp-sri#1]
Your plugin is not yet available for translating on [GlotPress](https://translate.wordpress.org/projects/wp-plugins/wp-sri).

I think it's because you're not [loading the plugin textdomain](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#loading-text-domain).

**Comment by meitar** [comment]
@GaryJones thanks for pointing that out.

**Comment by GaryJones** [comment]
Thanks - en_GB is now at 100%: https://translate.wordpress.org/projects/wp-plugins/wp-sri
