### ISSUE TITLE
Are the plugin still working?

### ISSUE THREAD

**Issue by sasha2002** [meitar/wp-sri#13]
Hi, have it been tested with latest WP?

**Comment by bgoewert** [comment]
Is it still working? Likely. WP is backwards compatible to some degree.
Has it been tested with latest WP? Assume no.

p.s., I have not tested it on latest WP either. I'm interested in an SRI plugin as well, but there is not enough time in the day to work on one.

**Comment by szepeviktor** [comment]
> WP is backwards compatible to some degree.

That degree is exactly 100%.

**Comment by fabacab** [comment]
Yeah, this is actually a pretty simple plugin.
