### ISSUE TITLE
Not catching Jetpack Stats

### ISSUE THREAD

**Issue by GaryJones** [meitar/wp-sri#2]
https://sritest.io/#report/a2513b13-a8f6-4625-a68c-70f255ddd9fe - most of the non-same-origin resources are caught and amended fine, but the stats.wp.com one is not.

**Comment by meitar** [comment]
Weird. How is that script being added to your WordPress page? (Is it via the JetPack plugin?)

**Comment by meitar** [comment]
Oh, I just found it. [Jetpack is adding this script by using a global variable](https://plugins.trac.wordpress.org/browser/jetpack/tags/4.0.2/modules/stats.php#L132). This is the "wrong way" to do this; it's not available for modification from other plugins. I'd suggest reporting this as a bug to the Jetpack team.

**Comment by GaryJones** [comment]
Pinging @kraftbj and @georgestephanis for insights.

**Comment by georgestephanis** [comment]
By my recollection, it was a workaround to ensure it printed even on
malformed themes that didn't do wp_head() and wp_footer().  Ooooold legacy
code.  Probably worth revisiting if there is a better workaround we could
do, but I wouldn't prioritize it too urgently.

**Comment by kraftbj** [comment]
Yeah, as George said, it was a workaround for themes lacking `wp_footer`. I'll open an issue in Jetpack to keep it trackable.
